### ISSUE TITLE
Version python para correr programas

### ISSUE THREAD

**Issue by UlisesGE** [beth-la/Python_class#8]
@beth-la me podríass decir k version de python utilizar para correr los scripts? [https://www.youtube.com/watch?v=TUxYTdlcUMw](url)

**Comment by beth-la** [comment]
> @beth-la me podríass decir k version de python utilizar para correr los scripts? [https://www.youtube.com/watch?v=TUxYTdlcUMw](url)
@UlisesGE Ño

**Comment by UlisesGE** [comment]
bale grasias
